# Generated by Django 2.2 on 2021-05-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_habr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300, unique=True, verbose_name='Заголовок статьи')),
                ('post_source', models.URLField(max_length=500, unique=True, verbose_name='Ссылка на источник')),
            ],
        ),
    ]
