# Generated by Django 2.2 on 2021-05-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_habr',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='post_habr',
            name='post_source',
            field=models.URLField(max_length=500, null=True, unique=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='post_habr',
            name='post_title',
            field=models.CharField(max_length=300, null=True, unique=True, verbose_name='Заголовок статьи'),
        ),
    ]
