# Generated by Django 2.2 on 2021-05-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_auto_20210525_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_dnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300, null=True, unique=True, verbose_name='Заголовок статьи')),
                ('post_source', models.URLField(max_length=500, null=True, unique=True, verbose_name='Ссылка на источник')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='post_itproger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300, null=True, unique=True, verbose_name='Заголовок статьи')),
                ('post_source', models.URLField(max_length=500, null=True, unique=True, verbose_name='Ссылка на источник')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Дата')),
            ],
        ),
    ]
