# Generated by Django 2.2 on 2021-05-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_post_dnews_post_itproger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post_itproger',
            new_name='post_tproger',
        ),
    ]
