# Generated by Django 2.2 on 2021-05-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_auto_20210526_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True, unique=True, verbose_name='Заголовок статьи')),
                ('source', models.URLField(max_length=500, null=True, unique=True, verbose_name='Ссылка на источник')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('img', models.URLField(max_length=500, null=True, verbose_name='favicon')),
            ],
        ),
        migrations.DeleteModel(
            name='post_dnews',
        ),
    ]
