# Generated by Django 2.2 on 2021-05-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_auto_20210527_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post_habr',
        ),
        migrations.DeleteModel(
            name='post_tproger',
        ),
    ]
